spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/network_dashboard
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none   # because table already exists
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8085   # or any free port
